run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: true
  go: '1.24'

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  formats: colored-line-number

issues:
  uniq-by-line: true


skip-dirs:
  - docs/

skip-files:
  - "*_gen\\.go$"

modules-download-mode: mod
allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - gofumpt
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - err113
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
    - prealloc
    - perfsprint

linters-settings:
  govet:
    settings:
      shadow:
        strict: true
    enable-all: true
  gocyclo:
    min-complexity: 50
  lll:
    line-length: 180
