package utils

import (
	"crypto/rand"
	"encoding/base64"
)

// UniqueBytesSize - number of bytes generated by UniqueBytesGenerator function
const UniqueBytesSize = 32

// UniqueStringGenerator - Generates crypto secure base64 encoded string
func UniqueStringGenerator() string {
	return base64.RawStdEncoding.EncodeToString(UniqueBytesGenerator())
}

// UniqueBytesGenerator generates crypto random bytes
func UniqueBytesGenerator() []byte {
	bytes := make([]byte, UniqueBytesSize)
	n, err := rand.Read(bytes)

	if err != nil || n != UniqueBytesSize {
		return nil
	}

	return bytes
}
