name: Docker Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        default: ""
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Needed for ARM64 Docker builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          push: true
          pull: true
          platforms: 'linux/amd64,linux/arm64/v8'
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: codeLieutenant/gofiber-boilerplate:${{ inputs.version }}
