name: Go

on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - "main.go"
    branches:
      - master
  pull_request:
    paths:
      - "app/**"
      - "main.go"
    branches:
      - master

jobs:
  build:
    name: Lint Test and Build
    runs-on: ubuntu-24.04
    steps:
      - name:
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          repo: gotestfmt
      - name: Build
        run: task build
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false"
      - name: Unit Tests
        run: |
	        cp config.example.yml config.yml
        	task test
